name: Enforce Develop Merge Policy

on:
  pull_request:
    branches:
      - develop

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          if [[ "${{ github.head_ref }}" != feature/* && "${{ github.head_ref }}" != backport/* ]]; then
            echo "Error: Only feature/* or backport/* branches can be merged into develop"
            echo "Your branch: ${{ github.head_ref }}"
            exit 1
          fi
